all: copyexec

copyexec:
	cp driverSIM* ../../../../exec/
	cp fona /etc/ppp/peers/fona
	cp fido /etc/ppp/peers/fido
	cp tim /etc/ppp/peers/tim
	cp rogers /etc/ppp/peers/rogers
	cp gprs /etc/chatscripts/gprs
	cp gprs_brasil /etc/chatsripts/gprs_brasil